### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by Owusu-Desmond**
# Final touches

In this pull request, I made the following changes

## Type of change

- [ ] Add a footer and some paragraphs description for the page.
- [ ] Adjust issues
- [ ] Style project

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @Owusu-Desmond , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good design
- All functionality working as expected.

## Required Changes ♻️
_Check the comments under the review._

- [ ] You are missing some of the linter checks like Lighthouse linter, Web hint linter. Kindly add these linters.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Owusu-Desmond** [comment]
Hi @muneebulrehman 

I followed the instructions [ JavaScript linters ](https://github.com/microverseinc/linters-config/tree/master/javascript) recommended for this module.

Please kindly check my code, I practice HTML best practices and I did not use inline CSS.

**Review by sumairq — CHANGES_REQUESTED** [review]
## Hi @Owusu-Desmond , 



Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good commit history
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Required Changes ♻️

-  [ ] As the previous reviewer asked, your project is missing webhint and lighthouse linters. You are supposed to add [html-css-js](https://github.com/microverseinc/linters-config/tree/master/html-css-js) linters.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Owusu-Desmond** [comment]
Hi @sumairq  

Please I followed the instructions [ JavaScript linters ](https://github.com/microverseinc/linters-config/tree/master/javascript) recommended for this module.

**Review by topeogunleye — APPROVED** [review]
### Hi @Owusu-Desmond, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
> ## [Optional] suggestions:
>- [ ] Next time, and for future Pull Requests,  please format your PR description in past tense.
> See a demo below:
pull_request_desc
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
